export const countryList = [
  { url: 'https://www.worldbank.org/en/country/afghanistan', countryName: 'Afghanistan' },
  { url: 'https://www.worldbank.org/en/country/albania', countryName: 'Albania' },
  { url: 'https://www.worldbank.org/sq/country/albania', countryName: 'Albania shqip' },
  { url: 'https://www.worldbank.org/en/where-we-work/algeria', countryName: 'Algeria' },
  { url: 'https://www.banquemondiale.org/fr/country/algeria', countryName: 'Algeria Français' },
  { url: 'https://www.albankaldawli.org/ar/country/algeria', countryName: 'Algeria عربي' },
  { url: 'https://www.worldbank.org/en/country/angola', countryName: 'Angola' },
  { url: 'https://www.worldbank.org/pt/country/angola', countryName: 'Angola Português' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'Antigua and Barbuda' },
  { url: 'https://www.worldbank.org/en/country/argentina', countryName: 'Argentina' },
  { url: 'https://www.bancomundial.org/es/country/argentina', countryName: 'Argentina Español' },
  { url: 'https://www.worldbank.org/en/country/armenia', countryName: 'Armenia' },
  { url: 'https://www.worldbank.org/en/country/australia', countryName: 'Australia' },
  { url: 'https://www.worldbank.org/en/country/austria', countryName: 'Austria' },
  { url: 'https://www.worldbank.org/en/country/azerbaijan', countryName: 'Azerbaijan' },
  { url: 'https://www.worldbank.org/en/country/gcc', countryName: 'Bahrain' },
  { url: 'https://www.worldbank.org/en/country/bangladesh', countryName: 'Bangladesh' },
  { url: 'https://www.worldbank.org/en/country/belarus', countryName: 'Belarus' },
  { url: 'https://www.vsemirnyjbank.org/ru/country/belarus', countryName: 'Belarus Русский' },
  { url: 'https://www.worldbank.org/en/country/belgium', countryName: 'Belgium' },
  { url: 'https://www.banquemondiale.org/fr/country/belgium', countryName: 'Belgium Français' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'Belize' },
  { url: 'https://www.worldbank.org/en/country/benin', countryName: 'Benin' },
  { url: 'https://www.banquemondiale.org/fr/country/benin', countryName: 'Benin Français' },
  { url: 'https://www.worldbank.org/en/country/bhutan', countryName: 'Bhutan' },
  { url: 'https://www.worldbank.org/en/country/bolivia', countryName: 'Bolivia' },
  { url: 'https://www.bancomundial.org/es/country/bolivia', countryName: 'Bolivia Español' },
  { url: 'https://www.worldbank.org/en/country/bosniaandherzegovina', countryName: 'Bosnia and Herzegovina' },
  { url: 'https://www.worldbank.org/en/country/botswana', countryName: 'Botswana' },
  { url: 'https://www.worldbank.org/en/country/brazil', countryName: 'Brazil' },
  { url: 'https://www.worldbank.org/pt/country/brazil', countryName: 'Brazil Português' },
  { url: 'https://www.worldbank.org/en/country/bulgaria', countryName: 'Bulgaria' },
  { url: 'https://www.worldbank.org/bg/country/bulgaria', countryName: 'Bulgaria Български' },
  { url: 'https://www.worldbank.org/en/country/burkinafaso', countryName: 'Burkina Faso' },
  { url: 'https://www.banquemondiale.org/fr/country/burkinafaso', countryName: 'Burkina Faso Français' },
  { url: 'https://www.worldbank.org/en/country/burundi', countryName: 'Burundi' },
  { url: 'https://www.banquemondiale.org/fr/country/burundi', countryName: 'Burundi Français' },
  { url: 'https://www.worldbank.org/en/country/caboverde', countryName: 'Cabo Verde' },
  { url: 'https://www.worldbank.org/pt/country/caboverde', countryName: 'Cabo Verde Português' },
  { url: 'https://www.worldbank.org/en/country/cambodia', countryName: 'Cambodia' },
  { url: 'https://www.worldbank.org/km/country/cambodia', countryName: 'Cambodia ភាសាខ្មែរ' },
  { url: 'https://www.worldbank.org/en/country/cameroon', countryName: 'Cameroon' },
  { url: 'https://www.banquemondiale.org/fr/country/cameroon', countryName: 'Cameroon Français' },
  { url: 'https://www.worldbank.org/en/country/canada', countryName: 'Canada' },
  { url: 'https://www.banquemondiale.org/fr/country/canada', countryName: 'Canada Français' },
  { url: 'https://www.worldbank.org/en/country/centralafricanrepublic', countryName: 'Central African Republic' },
  { url: 'https://www.banquemondiale.org/fr/country/centralafricanrepublic', countryName: 'Central African Republic Français' },
  { url: 'https://www.worldbank.org/en/country/chad', countryName: 'Chad' },
  { url: 'https://www.banquemondiale.org/fr/country/chad', countryName: 'Chad Français' },
  { url: 'https://www.worldbank.org/en/country/chile', countryName: 'Chile' },
  { url: 'https://www.bancomundial.org/es/country/chile', countryName: 'Chile Español' },
  { url: 'https://www.worldbank.org/en/country/china', countryName: 'China' },
  { url: 'https://www.shihang.org/zh/country/china', countryName: 'China 中文' },
  { url: 'https://www.worldbank.org/en/country/colombia', countryName: 'Colombia' },
  { url: 'https://www.bancomundial.org/es/country/colombia', countryName: 'Columbia Español' },
  { url: 'https://www.worldbank.org/en/country/comoros', countryName: 'Comoros' },
  { url: 'https://www.banquemondiale.org/fr/country/comoros', countryName: 'Comoros Français' },
  { url: 'https://www.worldbank.org/en/country/drc', countryName: 'Democratic Republic of Congo' },
  { url: 'https://www.banquemondiale.org/fr/country/drc', countryName: 'Democratic Republic of Congo Français' },
  { url: 'https://www.worldbank.org/en/country/congo', countryName: 'Republic of Congo' },
  { url: 'https://www.banquemondiale.org/fr/country/congo', countryName: 'Republic  of Congo Français' },
  { url: 'https://www.worldbank.org/en/country/costarica', countryName: 'Costa Rica' },
  { url: 'https://www.bancomundial.org/es/country/costarica', countryName: 'Costa Rica Español' },
  { url: 'https://www.worldbank.org/en/country/cotedivoire', countryName: "Cote d'Ivoire" },
  { url: 'https://www.banquemondiale.org/fr/country/cotedivoire', countryName: "Cote d'Ivoire Français" },
  { url: 'https://www.worldbank.org/en/country/croatia', countryName: 'Croatia' },
  { url: 'https://www.worldbank.org/en/country/eu', countryName: 'Czech Republic' },
  { url: 'https://www.worldbank.org/en/country/denmark', countryName: 'Denmark' },
  { url: 'https://www.worldbank.org/en/country/djibouti', countryName: 'Djibouti' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'Dominica' },
  { url: 'https://www.worldbank.org/en/country/dominicanrepublic', countryName: 'Dominican Republic' },
  { url: 'https://www.bancomundial.org/es/country/dominicanrepublic', countryName: 'Dominican Republic Español' },
  { url: 'https://www.worldbank.org/en/country/ecuador', countryName: 'Ecuador' },
  { url: 'https://www.bancomundial.org/es/country/ecuador', countryName: 'Ecuador Español' },
  { url: 'https://www.worldbank.org/en/country/egypt', countryName: 'Egypt' },
  { url: 'https://www.albankaldawli.org/ar/country/egypt', countryName: 'Egypt عربي' },
  { url: 'https://www.worldbank.org/en/country/elsalvador', countryName: 'El Salvador' },
  { url: 'https://www.bancomundial.org/es/country/elsalvador', countryName: 'El Salvador Español' },
  { url: 'https://www.worldbank.org/en/country/equatorialguinea', countryName: 'Equatorial Guinea' },
  { url: 'https://www.worldbank.org/en/country/eritrea', countryName: 'Eritrea' },
  { url: 'https://www.worldbank.org/en/country/estonia', countryName: 'Estonia' },
  { url: 'https://www.worldbank.org/en/country/ethiopia', countryName: 'Ethiopia' },
  { url: 'https://www.worldbank.org/en/country/westerneurope', countryName: 'Europe (Western)' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Fiji' },
  { url: 'https://www.worldbank.org/en/country/finland', countryName: 'Finland' },
  { url: 'https://www.worldbank.org/en/country/france', countryName: 'France' },
  { url: 'https://www.banquemondiale.org/fr/country/france', countryName: 'France Français' },
  { url: 'https://www.worldbank.org/en/country/gabon', countryName: 'Gabon' },
  { url: 'https://www.banquemondiale.org/fr/country/gabon', countryName: 'Gabon Français' },
  { url: 'https://www.worldbank.org/en/country/gambia', countryName: 'The Gambia' },
  { url: 'https://www.worldbank.org/en/country/georgia', countryName: 'Georgia' },
  { url: 'https://www.worldbank.org/en/country/germany', countryName: 'Germany' },
  { url: 'https://www.worldbank.org/en/country/ghana', countryName: 'Ghana' },
  { url: 'https://www.worldbank.org/en/country/greece', countryName: 'Greece' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'Grenada' },
  { url: 'https://www.worldbank.org/en/country/guatemala', countryName: 'Guatemala' },
  { url: 'https://www.bancomundial.org/es/country/guatemala', countryName: 'GuatemalamEspañol' },
  { url: 'https://www.worldbank.org/en/country/guinea', countryName: 'Guinea' },
  { url: 'https://www.banquemondiale.org/fr/country/guinea', countryName: 'Guinea Français' },
  { url: 'https://www.worldbank.org/en/country/guineabissau', countryName: 'Guinea-Bissau' },
  { url: 'https://www.worldbank.org/pt/country/guineabissau', countryName: 'Guinea-Bissau Português' },
  { url: 'https://www.worldbank.org/en/country/guineabissau', countryName: 'Guyana' },
  { url: 'https://www.worldbank.org/en/country/haiti', countryName: 'Haiti' },
  { url: 'https://www.banquemondiale.org/fr/country/haiti', countryName: 'Haiti Français' },
  { url: 'https://www.worldbank.org/en/country/honduras', countryName: 'Honduras' },
  { url: 'https://www.bancomundial.org/es/country/honduras', countryName: 'Honduras Español' },
  { url: 'https://www.worldbank.org/en/country/eu', countryName: 'Hungary' },
  { url: 'https://www.worldbank.org/en/country/iceland', countryName: 'Iceland' },
  { url: 'https://www.worldbank.org/en/country/india', countryName: 'India' },
  { url: 'https://www.worldbank.org/hi/country/india', countryName: 'India Hindi' },
  { url: 'https://www.worldbank.org/en/country/indonesia', countryName: 'Indonesia' },
  { url: 'https://www.worldbank.org/in/country/indonesia', countryName: 'Indonesia Bahasa' },
  { url: 'https://www.worldbank.org/en/country/iran', countryName: 'Iran' },
  { url: 'https://www.worldbank.org/en/country/iraq', countryName: 'Iraq' },
  { url: 'https://www.albankaldawli.org/ar/country/iraq', countryName: 'Iraq عربي' },
  { url: 'https://www.worldbank.org/en/country/israel', countryName: 'Israel' },
  { url: 'https://www.worldbank.org/en/country/italy', countryName: 'Italy' },
  { url: 'https://www.worldbank.org/en/country/jamaica', countryName: 'Jamaica' },
  { url: 'https://www.worldbank.org/en/country/japan', countryName: 'Japan' },
  { url: 'https://www.worldbank.org/ja/country/japan', countryName: 'Japan 日本語' },
  { url: 'https://www.worldbank.org/en/country/jordan', countryName: 'Jordan' },
  { url: 'https://www.albankaldawli.org/ar/country/jordan', countryName: 'Jordan عربي' },
  { url: 'https://www.worldbank.org/en/country/kazakhstan', countryName: 'Kazakhstan' },
  { url: 'https://www.vsemirnyjbank.org/ru/country/kazakhstan', countryName: 'Kazakhstan Русский' },
  { url: 'https://www.worldbank.org/en/country/kenya', countryName: 'Kenya' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Kiribati' },
  { url: 'https://www.worldbank.org/en/country/korea', countryName: 'Korea' },
  { url: 'https://www.worldbank.org/en/country/kosovo', countryName: 'Kosovo' },
  { url: 'https://www.worldbank.org/en/country/gcc', countryName: 'Kuwait' },
  { url: 'https://www.worldbank.org/en/country/kyrgyzrepublic', countryName: 'Kyrgyz Republic' },
  { url: 'https://www.vsemirnyjbank.org/ru/country/kyrgyzrepublic', countryName: 'Kyrgyz Republic Русский' },
  { url: 'https://www.worldbank.org/en/country/lao', countryName: 'Lao PDR' },
  { url: 'https://www.worldbank.org/en/country/latvia', countryName: 'Latvia' },
  { url: 'https://www.worldbank.org/en/country/lebanon', countryName: 'Lebanon' },
  { url: 'https://www.albankaldawli.org/ar/country/lebanon', countryName: 'Lebanon عربي' },
  { url: 'https://www.worldbank.org/en/country/lesotho', countryName: 'Lesotho' },
  { url: 'https://www.worldbank.org/en/country/liberia', countryName: 'Liberia' },
  { url: 'https://www.worldbank.org/en/country/libya', countryName: 'Libya' },
  { url: 'https://www.albankaldawli.org/ar/country/libya', countryName: 'Libya عربي' },
  { url: 'https://www.worldbank.org/en/country/lithuania', countryName: 'Lithuania' },
  { url: 'https://www.worldbank.org/en/country/luxembourg', countryName: 'Luxembourg' },
  { url: 'https://www.banquemondiale.org/fr/country/luxembourg', countryName: 'Luxembourg Français' },
  { url: 'https://www.worldbank.org/en/country/northmacedonia', countryName: 'FYR of Macedonia' },
  { url: 'https://www.worldbank.org/mk/country/macedonia', countryName: 'FYR of Macedonia македонски' },
  { url: 'https://www.worldbank.org/en/country/madagascar', countryName: 'Madagascar' },
  { url: 'https://www.banquemondiale.org/fr/country/madagascar', countryName: 'Madagascar Français' },
  { url: 'https://www.worldbank.org/en/country/malawi', countryName: 'Malawi' },
  { url: 'https://www.worldbank.org/en/country/malaysia', countryName: 'Malaysia' },
  { url: 'https://www.worldbank.org/en/country/maldives', countryName: 'Maldives' },
  { url: 'https://www.worldbank.org/en/country/mali', countryName: 'Mali' },
  { url: 'https://www.banquemondiale.org/fr/country/mali', countryName: 'Mali Français' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Marshall Islands' },
  { url: 'https://www.worldbank.org/en/country/mauritania', countryName: 'Mauritania' },
  { url: 'https://www.banquemondiale.org/fr/country/mauritania', countryName: 'Mauritania Français' },
  { url: 'https://www.worldbank.org/en/country/mauritius', countryName: 'Mauritius' },
  { url: 'https://www.banquemondiale.org/fr/country/mauritius', countryName: 'Mauritius Français' },
  { url: 'https://www.worldbank.org/en/country/mexico', countryName: 'Mexico' },
  { url: 'https://www.bancomundial.org/es/country/mexico', countryName: 'Mexico Español' },
  { url: 'https://www.worldbank.org/en/country/moldova', countryName: 'Moldova' },
  { url: 'https://www.worldbank.org/ro/country/moldova', countryName: 'Moldova română' },
  { url: 'https://www.worldbank.org/en/country/mongolia', countryName: 'Mongolia' },
  { url: 'https://www.worldbank.org/mn/country/mongolia', countryName: 'Mongolia Монгол' },
  { url: 'https://www.worldbank.org/en/country/montenegro', countryName: 'Montenegro' },
  { url: 'https://www.worldbank.org/en/country/morocco', countryName: 'Morocco' },
  { url: 'https://www.albankaldawli.org/ar/country/morocco', countryName: 'Morocco عربي' },
  { url: 'https://www.banquemondiale.org/fr/country/morocco', countryName: 'Morocco Français' },
  { url: 'https://www.worldbank.org/en/country/mozambique', countryName: 'Mozambique' },
  { url: 'https://www.worldbank.org/pt/country/mozambique', countryName: 'Mozambique Português' },
  { url: 'https://www.worldbank.org/en/country/myanmar', countryName: 'Myanmar' },
  { url: 'https://www.worldbank.org/en/country/namibia', countryName: 'Namibia' },
  { url: 'https://www.worldbank.org/en/country/nepal', countryName: 'Nepal' },
  { url: 'https://www.worldbank.org/en/country/netherlands', countryName: 'Netherlands' },
  { url: 'https://www.worldbank.org/en/country/nicaragua', countryName: 'Nicaragua' },
  { url: 'https://www.bancomundial.org/es/country/nicaragua', countryName: 'Nicaragua Español' },
  { url: 'https://www.worldbank.org/en/country/niger', countryName: 'Niger' },
  { url: 'https://www.banquemondiale.org/fr/country/niger', countryName: 'Niger Français' },
  { url: 'https://www.worldbank.org/en/country/nigeria', countryName: 'Nigeria' },
  { url: 'https://www.worldbank.org/en/country/norway', countryName: 'Norway' },
  { url: 'https://www.worldbank.org/en/country/gcc', countryName: 'Oman' },
  { url: 'https://www.worldbank.org/en/country/pakistan', countryName: 'Pakistan' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Palau' },
  { url: 'https://www.worldbank.org/en/country/panama', countryName: 'Panama' },
  { url: 'https://www.bancomundial.org/es/country/panama', countryName: 'Panama Español' },
  { url: 'https://www.worldbank.org/en/country/png', countryName: 'Papua New Guinea' },
  { url: 'https://www.worldbank.org/en/country/paraguay', countryName: 'Paraguay' },
  { url: 'https://www.bancomundial.org/es/country/paraguay', countryName: 'Paraguay Español' },
  { url: 'https://www.worldbank.org/en/country/peru', countryName: 'Peru' },
  { url: 'https://www.bancomundial.org/es/country/peru', countryName: 'Peru Español' },
  { url: 'https://www.worldbank.org/en/country/philippines', countryName: 'Philippines' },
  { url: 'https://www.worldbank.org/en/country/poland', countryName: 'Poland' },
  { url: 'https://www.worldbank.org/pl/country/poland', countryName: 'Poland Polski' },
  { url: 'https://www.worldbank.org/en/country/portugal', countryName: 'Portugal' },
  { url: 'https://www.worldbank.org/en/country/gcc', countryName: 'Qatar' },
  { url: 'https://www.worldbank.org/en/country/romania', countryName: 'Romania' },
  { url: 'https://www.worldbank.org/ro/country/romania', countryName: 'Romania Română' },
  { url: 'https://www.worldbank.org/en/country/russia', countryName: 'Russia' },
  { url: 'https://www.vsemirnyjbank.org/ru/country/russia', countryName: 'Russia Русский' },
  { url: 'https://www.worldbank.org/en/country/rwanda', countryName: 'Rwanda' },
  { url: 'https://www.banquemondiale.org/fr/country/rwanda', countryName: 'Rwanda Français' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Samoa' },
  { url: 'https://www.worldbank.org/en/country/saotome', countryName: 'Sao Tome and Principe' },
  { url: 'https://www.worldbank.org/pt/country/saotome', countryName: 'Sao Tome and Principe Português' },
  { url: 'https://www.worldbank.org/en/country/senegal', countryName: 'Senegal' },
  { url: 'https://www.banquemondiale.org/fr/country/senegal', countryName: 'Senegal Français' },
  { url: 'https://www.worldbank.org/en/country/serbia', countryName: 'Serbia' },
  { url: 'https://www.worldbank.org/en/country/seychelles', countryName: 'Seychelles' },
  { url: 'https://www.banquemondiale.org/fr/country/seychelles', countryName: 'Seychelles Français' },
  { url: 'https://www.worldbank.org/en/country/sierraleone', countryName: 'Sierra Leone' },
  { url: 'https://www.worldbank.org/en/country/singapore', countryName: 'Singapore' },
  { url: 'https://www.worldbank.org/en/country/eu', countryName: 'Slovak Republic' },
  { url: 'https://www.worldbank.org/en/country/eu', countryName: 'Slovenia' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Solomon Islands' },
  { url: 'https://www.worldbank.org/en/country/somalia', countryName: 'Federal Republic of Somalia' },
  { url: 'https://www.worldbank.org/en/country/southafrica', countryName: 'South Africa' },
  { url: 'https://www.worldbank.org/en/country/southsudan', countryName: 'South Sudan' },
  { url: 'https://www.worldbank.org/en/country/spain', countryName: 'Spain' },
  { url: 'https://www.bancomundial.org/es/country/spain', countryName: 'Spain Español' },
  { url: 'https://www.worldbank.org/en/country/srilanka', countryName: 'Sri Lanka' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'St. Kitts and Nevis' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'St. Lucia' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'St. Vincent and Grenadines' },
  { url: 'https://www.worldbank.org/en/country/sudan', countryName: 'Sudan' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'Suriname' },
  { url: 'https://www.worldbank.org/en/country/eswatini', countryName: 'Swaziland' },
  { url: 'https://www.worldbank.org/en/country/sweden', countryName: 'Sweden' },
  { url: 'https://www.worldbank.org/en/country/switzerland', countryName: 'Switzerland' },
  { url: 'https://www.worldbank.org/en/country/syria', countryName: 'Syria' },
  { url: 'https://www.albankaldawli.org/ar/country/syria', countryName: 'Syria عربي' },
  { url: 'https://www.worldbank.org/en/country/tajikistan', countryName: 'Tajikistan' },
  { url: 'https://www.vsemirnyjbank.org/ru/country/tajikistan', countryName: 'Tajikistan Русский' },
  { url: 'https://www.worldbank.org/en/country/tanzania', countryName: 'Tanzania' },
  { url: 'https://www.worldbank.org/en/country/thailand', countryName: 'Thailand' },
  { url: 'https://www.worldbank.org/th/country/thailand', countryName: 'Thailand ภาษาไทย' },
  { url: 'https://www.worldbank.org/en/country/timor-leste', countryName: 'Timor Leste (East Timor)' },
  { url: 'https://www.worldbank.org/en/country/togo', countryName: 'Togo' },
  { url: 'https://www.banquemondiale.org/fr/country/togo', countryName: 'Togo Français' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Tonga' },
  { url: 'https://www.worldbank.org/en/country/caribbean', countryName: 'Trinidad and Tobago' },
  { url: 'https://www.worldbank.org/en/country/tunisia', countryName: 'Tunisia' },
  { url: 'https://www.albankaldawli.org/ar/country/tunisia', countryName: 'Tunisia عربي' },
  { url: 'https://www.banquemondiale.org/fr/country/tunisia', countryName: 'Tunisia Français' },
  { url: 'https://www.worldbank.org/en/country/turkey', countryName: 'Turkey' },
  { url: 'https://www.worldbank.org/en/country/turkmenistan', countryName: 'Turkmenistan' },
  { url: 'https://www.vsemirnyjbank.org/ru/country/turkmenistan', countryName: 'Turkmenistan Русский' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Tuvalu' },
  { url: 'https://www.worldbank.org/en/country/uganda', countryName: 'Uganda' },
  { url: 'https://www.worldbank.org/en/country/ukraine', countryName: 'Ukraine' },
  { url: 'https://www.worldbank.org/uk/country/ukraine', countryName: 'Ukraine Yкраїнський' },
  { url: 'https://www.worldbank.org/en/country/gcc', countryName: 'United Arab Emirates' },
  { url: 'https://www.worldbank.org/en/country/unitedkingdom', countryName: 'United Kingdom' },
  { url: 'https://www.worldbank.org/en/country/unitedstates', countryName: 'United States of America' },
  { url: 'https://www.worldbank.org/en/country/uruguay', countryName: 'Uruguay' },
  { url: 'https://www.bancomundial.org/es/country/uruguay', countryName: 'Uruguay Español' },
  { url: 'https://www.worldbank.org/en/country/uzbekistan', countryName: 'Uzbekistan' },
  { url: 'https://www.vsemirnyjbank.org/ru/country/uzbekistan', countryName: 'Uzbekistan Русский' },
  { url: 'https://www.worldbank.org/en/country/pacificislands', countryName: 'Vanuatu' },
  { url: 'https://www.worldbank.org/en/country/venezuela', countryName: 'Venezuela' },
  { url: 'https://www.bancomundial.org/es/country/venezuela', countryName: 'Venezuela Español' },
  { url: 'https://www.worldbank.org/en/country/vietnam', countryName: 'Vietnam' },
  { url: 'https://www.worldbank.org/vi/country/vietnam', countryName: 'Vietnam Tiẽng Việt' },
  { url: 'https://www.worldbank.org/en/country/westbankandgaza', countryName: 'West Bank and Gaza' },
  { url: 'https://www.albankaldawli.org/ar/country/westbankandgaza', countryName: 'West Bank and Gaza عربي' },
  { url: 'https://www.worldbank.org/en/country/yemen', countryName: 'Yemen' },
  { url: 'https://www.albankaldawli.org/ar/country/yemen', countryName: 'Yemen عربي' },
  { url: 'https://www.worldbank.org/en/country/zambia', countryName: 'Zambia' },
  { url: 'https://www.worldbank.org/en/country/zimbabwe', countryName: 'Zimbabwe' },
];

export default countryList;
